### ISSUE TITLE
python2 unicode display issue, opening the file fails to missing __next__ attribute

### ISSUE THREAD

**Issue by jgrewe** [G-Node/odml-ui#26]
Welcome screen that offers the list of recent files shows unicode "\u2022" instead of the dots...

Opening a file in python2 leads to 

````
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pygtkcompat/generictreemodel.py", line 60, in wrapped_func
    return func(*args, **kargs)
  File "/usr/lib/python2.7/dist-packages/pygtkcompat/generictreemodel.py", line 240, in do_iter_next
    next_data = self.on_iter_next(self.get_user_data(iter))
  File "/home/.../projects/programming/odml-ui/odmlui/treemodel/TreeModel.py", line 107, in on_iter_next
    next = tree_iter.get_next()
  File "/home/.../projects/programming/odml-ui/odmlui/treemodel/GenericIter.py", line 44, in get_next
    obj = self._obj.__next__()
AttributeError: 'Property' object has no attribute '__next__'
````

**Comment by digaru19** [comment]
I think the missing \_\_next\_\_ attribute issue has been fixed in the odML core library, in the **odml/tools/nodes/ParentedNode**, in which we aliased **\_\_next\_\_** to **next**.
If this issue persists even with the above changes, then I'll look into it again.
